apiVersion: apps/v1
kind: Deployment
metadata:
  name: hc-vault
  namespace: hc
spec:
  selector:
    matchLabels:
      app: hc-vault
  template:
    metadata:
      labels:
        app: hc-vault
    spec:
      containers:
        - name: hc-vault
          image: vault:1.9.8
          imagePullPolicy: IfNotPresent
          env:
            - name: VAULT_ADDR
              value: 'http://0.0.0.0:8200'
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value : "vault_token"
            - name: VAULT_API_ADDR
              value: "http://0.0.0.0:8200"
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          ports:
            - containerPort: 8200
