apiVersion: v1
kind: Service
metadata:
  name: hc-vault-service
  namespace: hc
spec:
  selector:
    app: hc-vault
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 8200
      nodePort: 30036
      targetPort: 8200
